[package]
name = "osm-dijkstra-pre"
version = "1.0.0"
authors = [ "Felix Buehler <account@buehler.rocks>" ]

include = [
  "README.md",
  ".gitignore",
  "Cargo.toml",
  "src/*.rs"
]

[dependencies]
bincode = "1.2"
osmpbfreader = "0.13"
serde = { version = "1.0", features = ["derive"] }
