name: osm-dijkstra

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build pre
      run: |
        cd ./pre/
        cargo build --verbose
    - name: Build web
      run: |
        cd ./web/
        cargo build --verbose
    - name: Run pre tests
      run: |
        cd ./pre/
        cargo test --verbose
    - name: Run web tests
      run: |
        cd ./web/
        cargo test --verbose
