name: osm-dijkstra

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build pre
      run: |
        cargo build --verbose -p osm-dijkstra-pre
    - name: Build web
      run: |
        cargo build --verbose -p osm-dijkstra-web
    - name: Run pre tests
      run: |
        cargo test --verbose -p osm-dijkstra-pre
    - name: Run web tests
      run: |
        cargo test --verbose -p osm-dijkstra-web
